# Generated by Django 6.1.1 on 2026-10-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
